[project]
name = "ai-engineering-2026"
version = "0.1.0"
description = "concept summaries based on AI Makerspace bootcamp curriculum agenda"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
